//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2
use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "movement_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub product: i32,
    pub movement: i32,
    pub stock: i32,
    pub result: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct AddDto {
    pub product: i32,
    pub movement: i32,
    pub stock: i32,
    pub result: i32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UpdateDto {
    pub id: i32,
    pub product: i32,
    pub movement: i32,
    pub stock: i32,
    pub result: i32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct DoMovementDto {
    pub id: i32,
    pub product: i32,
    pub movement: i32,
    pub count: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommonDto {
    pub id: i32,
    pub product: i32,
    pub movement: i32,
    pub stock: i32,
    pub result: i32,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
pub struct Filter {
    pub product: i32,
    pub deleted: Option<bool>, // if true => deleted_at IS NULL
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
